// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Constant byte

const (
	ConstantFRAGMENT Constant = 32
	ConstantBATCH_SZ Constant = 64
)

var EnumNamesConstant = map[Constant]string{
	ConstantFRAGMENT: "FRAGMENT",
	ConstantBATCH_SZ: "BATCH_SZ",
}

var EnumValuesConstant = map[string]Constant{
	"FRAGMENT": ConstantFRAGMENT,
	"BATCH_SZ": ConstantBATCH_SZ,
}

func (v Constant) String() string {
	if s, ok := EnumNamesConstant[v]; ok {
		return s
	}
	return "Constant(" + strconv.FormatInt(int64(v), 10) + ")"
}
