// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Marker byte

const (
	MarkerSENTINEL Marker = 0
	MarkerSOH      Marker = 1
	MarkerEOE      Marker = 2
	MarkerSOO      Marker = 3
	MarkerEOO      Marker = 4
	MarkerSOA      Marker = 5
	MarkerEOA      Marker = 6
	MarkerAED      Marker = 7
	MarkerAEE      Marker = 8
	MarkerTEXT     Marker = 9
	MarkerFRAG     Marker = 10
	MarkerINT8     Marker = 11
	MarkerUINT8    Marker = 12
	MarkerINT16    Marker = 13
	MarkerUINT16   Marker = 14
	MarkerINT32    Marker = 15
	MarkerUINT32   Marker = 16
	MarkerDATE32   Marker = 17
	MarkerFLT32    Marker = 18
	MarkerINT64    Marker = 19
	MarkerUINT64   Marker = 20
	MarkerDATE64   Marker = 21
	MarkerFLT64    Marker = 22
	MarkerBOOL     Marker = 23
	MarkerNULL     Marker = 24
	MarkerJSON     Marker = 25
	MarkerMAX      Marker = 31
)

var EnumNamesMarker = map[Marker]string{
	MarkerSENTINEL: "SENTINEL",
	MarkerSOH:      "SOH",
	MarkerEOE:      "EOE",
	MarkerSOO:      "SOO",
	MarkerEOO:      "EOO",
	MarkerSOA:      "SOA",
	MarkerEOA:      "EOA",
	MarkerAED:      "AED",
	MarkerAEE:      "AEE",
	MarkerTEXT:     "TEXT",
	MarkerFRAG:     "FRAG",
	MarkerINT8:     "INT8",
	MarkerUINT8:    "UINT8",
	MarkerINT16:    "INT16",
	MarkerUINT16:   "UINT16",
	MarkerINT32:    "INT32",
	MarkerUINT32:   "UINT32",
	MarkerDATE32:   "DATE32",
	MarkerFLT32:    "FLT32",
	MarkerINT64:    "INT64",
	MarkerUINT64:   "UINT64",
	MarkerDATE64:   "DATE64",
	MarkerFLT64:    "FLT64",
	MarkerBOOL:     "BOOL",
	MarkerNULL:     "NULL",
	MarkerJSON:     "JSON",
	MarkerMAX:      "MAX",
}

var EnumValuesMarker = map[string]Marker{
	"SENTINEL": MarkerSENTINEL,
	"SOH":      MarkerSOH,
	"EOE":      MarkerEOE,
	"SOO":      MarkerSOO,
	"EOO":      MarkerEOO,
	"SOA":      MarkerSOA,
	"EOA":      MarkerEOA,
	"AED":      MarkerAED,
	"AEE":      MarkerAEE,
	"TEXT":     MarkerTEXT,
	"FRAG":     MarkerFRAG,
	"INT8":     MarkerINT8,
	"UINT8":    MarkerUINT8,
	"INT16":    MarkerINT16,
	"UINT16":   MarkerUINT16,
	"INT32":    MarkerINT32,
	"UINT32":   MarkerUINT32,
	"DATE32":   MarkerDATE32,
	"FLT32":    MarkerFLT32,
	"INT64":    MarkerINT64,
	"UINT64":   MarkerUINT64,
	"DATE64":   MarkerDATE64,
	"FLT64":    MarkerFLT64,
	"BOOL":     MarkerBOOL,
	"NULL":     MarkerNULL,
	"JSON":     MarkerJSON,
	"MAX":      MarkerMAX,
}

func (v Marker) String() string {
	if s, ok := EnumNamesMarker[v]; ok {
		return s
	}
	return "Marker(" + strconv.FormatInt(int64(v), 10) + ")"
}
