// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type MetadataKey byte

const (
	MetadataKeyUNKNOWN  MetadataKey = 0
	MetadataKeyNEXTCODE MetadataKey = 1
	MetadataKeyCODEPATH MetadataKey = 2
	MetadataKeyLAYOUT   MetadataKey = 3
)

var EnumNamesMetadataKey = map[MetadataKey]string{
	MetadataKeyUNKNOWN:  "UNKNOWN",
	MetadataKeyNEXTCODE: "NEXTCODE",
	MetadataKeyCODEPATH: "CODEPATH",
	MetadataKeyLAYOUT:   "LAYOUT",
}

var EnumValuesMetadataKey = map[string]MetadataKey{
	"UNKNOWN":  MetadataKeyUNKNOWN,
	"NEXTCODE": MetadataKeyNEXTCODE,
	"CODEPATH": MetadataKeyCODEPATH,
	"LAYOUT":   MetadataKeyLAYOUT,
}

func (v MetadataKey) String() string {
	if s, ok := EnumNamesMetadataKey[v]; ok {
		return s
	}
	return "MetadataKey(" + strconv.FormatInt(int64(v), 10) + ")"
}
